import Link from "next/link";

export default function ProjectsPage() {
  return (
    <main>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Grass</p>
        <div className="bg-grass-1 w-full h-20" />
        <div className="bg-grass-2 w-full h-20" />
        <div className="bg-grass-3 w-full h-20" />
        <div className="bg-grass-4 w-full h-20" />
        <div className="bg-grass-5 w-full h-20" />
        <div className="bg-grass-6 w-full h-20" />
        <div className="bg-grass-7 w-full h-20" />
        <div className="bg-grass-8 w-full h-20" />
        <div className="bg-grass-9 w-full h-20" />
        <div className="bg-grass-10 w-full h-20" />
        <div className="bg-grass-11 w-full h-20" />
        <div className="bg-grass-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Mint</p>
        <div className="bg-mint-1 w-full h-20" />
        <div className="bg-mint-2 w-full h-20" />
        <div className="bg-mint-3 w-full h-20" />
        <div className="bg-mint-4 w-full h-20" />
        <div className="bg-mint-5 w-full h-20" />
        <div className="bg-mint-6 w-full h-20" />
        <div className="bg-mint-7 w-full h-20" />
        <div className="bg-mint-8 w-full h-20" />
        <div className="bg-mint-9 w-full h-20" />
        <div className="bg-mint-10 w-full h-20" />
        <div className="bg-mint-11 w-full h-20" />
        <div className="bg-mint-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Sky</p>
        <div className="bg-sky-1 w-full h-20" />
        <div className="bg-sky-2 w-full h-20" />
        <div className="bg-sky-3 w-full h-20" />
        <div className="bg-sky-4 w-full h-20" />
        <div className="bg-sky-5 w-full h-20" />
        <div className="bg-sky-6 w-full h-20" />
        <div className="bg-sky-7 w-full h-20" />
        <div className="bg-sky-8 w-full h-20" />
        <div className="bg-sky-9 w-full h-20" />
        <div className="bg-sky-10 w-full h-20" />
        <div className="bg-sky-11 w-full h-20" />
        <div className="bg-sky-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Plum</p>
        <div className="bg-plum-1 w-full h-20" />
        <div className="bg-plum-2 w-full h-20" />
        <div className="bg-plum-3 w-full h-20" />
        <div className="bg-plum-4 w-full h-20" />
        <div className="bg-plum-5 w-full h-20" />
        <div className="bg-plum-6 w-full h-20" />
        <div className="bg-plum-7 w-full h-20" />
        <div className="bg-plum-8 w-full h-20" />
        <div className="bg-plum-9 w-full h-20" />
        <div className="bg-plum-10 w-full h-20" />
        <div className="bg-plum-11 w-full h-20" />
        <div className="bg-plum-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Purple</p>
        <div className="bg-purple-1 w-full h-20" />
        <div className="bg-purple-2 w-full h-20" />
        <div className="bg-purple-3 w-full h-20" />
        <div className="bg-purple-4 w-full h-20" />
        <div className="bg-purple-5 w-full h-20" />
        <div className="bg-purple-6 w-full h-20" />
        <div className="bg-purple-7 w-full h-20" />
        <div className="bg-purple-8 w-full h-20" />
        <div className="bg-purple-9 w-full h-20" />
        <div className="bg-purple-10 w-full h-20" />
        <div className="bg-purple-11 w-full h-20" />
        <div className="bg-purple-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Ruby</p>
        <div className="bg-ruby-1 w-full h-20" />
        <div className="bg-ruby-2 w-full h-20" />
        <div className="bg-ruby-3 w-full h-20" />
        <div className="bg-ruby-4 w-full h-20" />
        <div className="bg-ruby-5 w-full h-20" />
        <div className="bg-ruby-6 w-full h-20" />
        <div className="bg-ruby-7 w-full h-20" />
        <div className="bg-ruby-8 w-full h-20" />
        <div className="bg-ruby-9 w-full h-20" />
        <div className="bg-ruby-10 w-full h-20" />
        <div className="bg-ruby-11 w-full h-20" />
        <div className="bg-ruby-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Tomato</p>
        <div className="bg-tomato-1 w-full h-20" />
        <div className="bg-tomato-2 w-full h-20" />
        <div className="bg-tomato-3 w-full h-20" />
        <div className="bg-tomato-4 w-full h-20" />
        <div className="bg-tomato-5 w-full h-20" />
        <div className="bg-tomato-6 w-full h-20" />
        <div className="bg-tomato-7 w-full h-20" />
        <div className="bg-tomato-8 w-full h-20" />
        <div className="bg-tomato-9 w-full h-20" />
        <div className="bg-tomato-10 w-full h-20" />
        <div className="bg-tomato-11 w-full h-20" />
        <div className="bg-tomato-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Orange</p>
        <div className="bg-orange-1 w-full h-20" />
        <div className="bg-orange-2 w-full h-20" />
        <div className="bg-orange-3 w-full h-20" />
        <div className="bg-orange-4 w-full h-20" />
        <div className="bg-orange-5 w-full h-20" />
        <div className="bg-orange-6 w-full h-20" />
        <div className="bg-orange-7 w-full h-20" />
        <div className="bg-orange-8 w-full h-20" />
        <div className="bg-orange-9 w-full h-20" />
        <div className="bg-orange-10 w-full h-20" />
        <div className="bg-orange-11 w-full h-20" />
        <div className="bg-orange-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Amber</p>
        <div className="bg-amber-1 w-full h-20" />
        <div className="bg-amber-2 w-full h-20" />
        <div className="bg-amber-3 w-full h-20" />
        <div className="bg-amber-4 w-full h-20" />
        <div className="bg-amber-5 w-full h-20" />
        <div className="bg-amber-6 w-full h-20" />
        <div className="bg-amber-7 w-full h-20" />
        <div className="bg-amber-8 w-full h-20" />
        <div className="bg-amber-9 w-full h-20" />
        <div className="bg-amber-10 w-full h-20" />
        <div className="bg-amber-11 w-full h-20" />
        <div className="bg-amber-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Brown</p>
        <div className="bg-brown-1 w-full h-20" />
        <div className="bg-brown-2 w-full h-20" />
        <div className="bg-brown-3 w-full h-20" />
        <div className="bg-brown-4 w-full h-20" />
        <div className="bg-brown-5 w-full h-20" />
        <div className="bg-brown-6 w-full h-20" />
        <div className="bg-brown-7 w-full h-20" />
        <div className="bg-brown-8 w-full h-20" />
        <div className="bg-brown-9 w-full h-20" />
        <div className="bg-brown-10 w-full h-20" />
        <div className="bg-brown-11 w-full h-20" />
        <div className="bg-brown-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">red</p>
        <div className="bg-yellow-1 w-full h-20" />
        <div className="bg-yellow-2 w-full h-20" />
        <div className="bg-yellow-3 w-full h-20" />
        <div className="bg-yellow-4 w-full h-20" />
        <div className="bg-yellow-5 w-full h-20" />
        <div className="bg-yellow-6 w-full h-20" />
        <div className="bg-yellow-7 w-full h-20" />
        <div className="bg-yellow-8 w-full h-20" />
        <div className="bg-yellow-9 w-full h-20" />
        <div className="bg-yellow-10 w-full h-20" />
        <div className="bg-yellow-11 w-full h-20" />
        <div className="bg-yellow-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Red</p>
        <div className="bg-red-1 w-full h-20" />
        <div className="bg-red-2 w-full h-20" />
        <div className="bg-red-3 w-full h-20" />
        <div className="bg-red-4 w-full h-20" />
        <div className="bg-red-5 w-full h-20" />
        <div className="bg-red-6 w-full h-20" />
        <div className="bg-red-7 w-full h-20" />
        <div className="bg-red-8 w-full h-20" />
        <div className="bg-red-9 w-full h-20" />
        <div className="bg-red-10 w-full h-20" />
        <div className="bg-red-11 w-full h-20" />
        <div className="bg-red-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Crimson</p>
        <div className="bg-crimson-1 w-full h-20" />
        <div className="bg-crimson-2 w-full h-20" />
        <div className="bg-crimson-3 w-full h-20" />
        <div className="bg-crimson-4 w-full h-20" />
        <div className="bg-crimson-5 w-full h-20" />
        <div className="bg-crimson-6 w-full h-20" />
        <div className="bg-crimson-7 w-full h-20" />
        <div className="bg-crimson-8 w-full h-20" />
        <div className="bg-crimson-9 w-full h-20" />
        <div className="bg-crimson-10 w-full h-20" />
        <div className="bg-crimson-11 w-full h-20" />
        <div className="bg-crimson-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Pink</p>
        <div className="bg-pink-1 w-full h-20" />
        <div className="bg-pink-2 w-full h-20" />
        <div className="bg-pink-3 w-full h-20" />
        <div className="bg-pink-4 w-full h-20" />
        <div className="bg-pink-5 w-full h-20" />
        <div className="bg-pink-6 w-full h-20" />
        <div className="bg-pink-7 w-full h-20" />
        <div className="bg-pink-8 w-full h-20" />
        <div className="bg-pink-9 w-full h-20" />
        <div className="bg-pink-10 w-full h-20" />
        <div className="bg-pink-11 w-full h-20" />
        <div className="bg-pink-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Violet</p>
        <div className="bg-violet-1 w-full h-20" />
        <div className="bg-violet-2 w-full h-20" />
        <div className="bg-violet-3 w-full h-20" />
        <div className="bg-violet-4 w-full h-20" />
        <div className="bg-violet-5 w-full h-20" />
        <div className="bg-violet-6 w-full h-20" />
        <div className="bg-violet-7 w-full h-20" />
        <div className="bg-violet-8 w-full h-20" />
        <div className="bg-violet-9 w-full h-20" />
        <div className="bg-violet-10 w-full h-20" />
        <div className="bg-violet-11 w-full h-20" />
        <div className="bg-violet-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Iris</p>
        <div className="bg-iris-1 w-full h-20" />
        <div className="bg-iris-2 w-full h-20" />
        <div className="bg-iris-3 w-full h-20" />
        <div className="bg-iris-4 w-full h-20" />
        <div className="bg-iris-5 w-full h-20" />
        <div className="bg-iris-6 w-full h-20" />
        <div className="bg-iris-7 w-full h-20" />
        <div className="bg-iris-8 w-full h-20" />
        <div className="bg-iris-9 w-full h-20" />
        <div className="bg-iris-10 w-full h-20" />
        <div className="bg-iris-11 w-full h-20" />
        <div className="bg-iris-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Indigo</p>
        <div className="bg-indigo-1 w-full h-20" />
        <div className="bg-indigo-2 w-full h-20" />
        <div className="bg-indigo-3 w-full h-20" />
        <div className="bg-indigo-4 w-full h-20" />
        <div className="bg-indigo-5 w-full h-20" />
        <div className="bg-indigo-6 w-full h-20" />
        <div className="bg-indigo-7 w-full h-20" />
        <div className="bg-indigo-8 w-full h-20" />
        <div className="bg-indigo-9 w-full h-20" />
        <div className="bg-indigo-10 w-full h-20" />
        <div className="bg-indigo-11 w-full h-20" />
        <div className="bg-indigo-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Blue</p>
        <div className="bg-blue-1 w-full h-20" />
        <div className="bg-blue-2 w-full h-20" />
        <div className="bg-blue-3 w-full h-20" />
        <div className="bg-blue-4 w-full h-20" />
        <div className="bg-blue-5 w-full h-20" />
        <div className="bg-blue-6 w-full h-20" />
        <div className="bg-blue-7 w-full h-20" />
        <div className="bg-blue-8 w-full h-20" />
        <div className="bg-blue-9 w-full h-20" />
        <div className="bg-blue-10 w-full h-20" />
        <div className="bg-blue-11 w-full h-20" />
        <div className="bg-blue-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Cyan</p>
        <div className="bg-cyan-1 w-full h-20" />
        <div className="bg-cyan-2 w-full h-20" />
        <div className="bg-cyan-3 w-full h-20" />
        <div className="bg-cyan-4 w-full h-20" />
        <div className="bg-cyan-5 w-full h-20" />
        <div className="bg-cyan-6 w-full h-20" />
        <div className="bg-cyan-7 w-full h-20" />
        <div className="bg-cyan-8 w-full h-20" />
        <div className="bg-cyan-9 w-full h-20" />
        <div className="bg-cyan-10 w-full h-20" />
        <div className="bg-cyan-11 w-full h-20" />
        <div className="bg-cyan-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Teal</p>
        <div className="bg-teal-1 w-full h-20" />
        <div className="bg-teal-2 w-full h-20" />
        <div className="bg-teal-3 w-full h-20" />
        <div className="bg-teal-4 w-full h-20" />
        <div className="bg-teal-5 w-full h-20" />
        <div className="bg-teal-6 w-full h-20" />
        <div className="bg-teal-7 w-full h-20" />
        <div className="bg-teal-8 w-full h-20" />
        <div className="bg-teal-9 w-full h-20" />
        <div className="bg-teal-10 w-full h-20" />
        <div className="bg-teal-11 w-full h-20" />
        <div className="bg-teal-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Jade</p>
        <div className="bg-jade-1 w-full h-20" />
        <div className="bg-jade-2 w-full h-20" />
        <div className="bg-jade-3 w-full h-20" />
        <div className="bg-jade-4 w-full h-20" />
        <div className="bg-jade-5 w-full h-20" />
        <div className="bg-jade-6 w-full h-20" />
        <div className="bg-jade-7 w-full h-20" />
        <div className="bg-jade-8 w-full h-20" />
        <div className="bg-jade-9 w-full h-20" />
        <div className="bg-jade-10 w-full h-20" />
        <div className="bg-jade-11 w-full h-20" />
        <div className="bg-jade-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Green</p>
        <div className="bg-green-1 w-full h-20" />
        <div className="bg-green-2 w-full h-20" />
        <div className="bg-green-3 w-full h-20" />
        <div className="bg-green-4 w-full h-20" />
        <div className="bg-green-5 w-full h-20" />
        <div className="bg-green-6 w-full h-20" />
        <div className="bg-green-7 w-full h-20" />
        <div className="bg-green-8 w-full h-20" />
        <div className="bg-green-9 w-full h-20" />
        <div className="bg-green-10 w-full h-20" />
        <div className="bg-green-11 w-full h-20" />
        <div className="bg-green-12 w-full h-20" />
      </div>
      <div className="grid grid-cols-12 ">
        <p className="col-span-12 my-2">Lime</p>
        <div className="bg-lime-1 w-full h-20" />
        <div className="bg-lime-2 w-full h-20" />
        <div className="bg-lime-3 w-full h-20" />
        <div className="bg-lime-4 w-full h-20" />
        <div className="bg-lime-5 w-full h-20" />
        <div className="bg-lime-6 w-full h-20" />
        <div className="bg-lime-7 w-full h-20" />
        <div className="bg-lime-8 w-full h-20" />
        <div className="bg-lime-9 w-full h-20" />
        <div className="bg-lime-10 w-full h-20" />
        <div className="bg-lime-11 w-full h-20" />
        <div className="bg-lime-12 w-full h-20" />
      </div>
    </main>
  );
}
